backend:
  name: github
  repo: RofiSyahrul/personal-web
  branch: master

publish_mode: editorial_workflow

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

logo_url: 'https://rofisyahrul.com/icons/favicon.ico'

collections:
  - name: 'config'
    label: 'Config'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Config'
        file: 'config.json'
        description: 'General site settings'
        fields:
          - label: 'URL'
            name: 'base_url'
            widget: 'string'
            hint: 'Do not enter the trailing slash of the URL'
          - label: 'App Name'
            name: 'app_name'
            widget: 'string'
            hint: 'Shown when user add site to their homescreen'
          - label: 'Site title'
            name: 'site_title'
            widget: 'string'
          - label: 'Site author'
            name: 'site_author'
            widget: 'string'
          - label: 'Site description'
            name: 'site_description'
            widget: 'string'
          - label: 'Site keywords'
            name: 'site_keywords'
            widget: 'list'
            summary: '{{fields.keyword.keyword}}'
            field:
              label: Keyword
              name: keyword
              widget: 'string'
          - label: 'Twitter account'
            name: 'twitter_account'
            widget: 'string'
          - label: 'GitHub account'
            name: 'github_account'
            widget: 'string'

  - name: 'meta'
    label: 'Meta'
    delete: false
    editor:
      preview: false
    files:
      - name: 'tags'
        label: 'Tags'
        file: '_meta/tags.yml'
        description: 'List of tags'
        fields:
          - name: tags
            label: Tags
            label_singular: 'Tag'
            widget: list
            fields:
              - label: 'Slug'
                name: 'slug'
                widget: 'string'
                hint: 'The part of a URL identifies the tag'
              - label: 'Display Name'
                name: 'name'
                widget: 'string'
                hint: 'Tag name for displaying on the site'

  # - name: 'cv'
  #   label: 'CV'
  #   create: true

  - name: 'posts'
    label: 'Posts'
    label_singular: 'Post'
    folder: '_content/posts/'
    extension: 'mdx'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    identifier_field: slug
    summary: '{{title}}'
    fields:
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        dateFormat: 'YYYY-MM-DD'
        timeFormat: false
        valueField: 'authors.*.slug'
      - label: Tags
        label_singular: 'Tag'
        name: 'tags'
        widget: list
        summary: '{{fields.tag}}'
        field:
          label: Tag
          name: tag
          widget: relation
          collection: 'meta'
          file: 'tags'
          searchFields:
            - 'tags.*.name'
            - 'tags.*.slug'
          displayFields:
            - 'tags.*.name'
          valueField: 'tags.*.slug'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
